Add files via upload

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -49,6 +49,19 @@ jobs:
 # .Rprofile
 # renv/
 # after init(), install new package with install.packages(), add it with renv::snapshot()
+      - name: Create gh-pages branch if missing
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          if ! git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
+            echo "Branch gh-pages not found. Creating it..."
+            git checkout --orphan gh-pages
+            git rm -rf .
+            git commit --allow-empty -m "Initial gh-pages branch"
+            git push origin gh-pages
+            git checkout main
+          fi
+
       - name: Render and Publish
         uses: quarto-dev/quarto-actions/publish@v2
         with:
